-- Codigo de aplicacion : 104 (SISPLAN)

-- APP
insert into SISSEGUMD.ac_grupo (GRUPOCOD,DESCRIPCION,SITUACION,SIGLAS,CARPETA,URL,UBICACION,TIPO,ICON,URLICON,VERSION,ACCESO,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE,ESTADO,USUCODRES,ORDEN)
	values (104,'SISTEMA PLANIFICACION Y PRESUPUESTO','A','SISPLAN','SISPLAN','http://10.24.9.78/sisplan/','E','W','partediario.png','http://10.24.9.6:8080/icon/','1.0','U','ADMIN','ADMIN',sysdate,sysdate,1,null,1);

-- ROLES
insert into SISSEGUMD.ac_rol (ROLCOD,DESCRIPCION,SITUACION,SIGLAS,GRUPOCOD,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE,ESTADO,ADMIN)
	VALUES (314,'Rol Administrador','A','ROLE_ADMIN',104,'ADMIN','ADMIN',sysdate,sysdate,1,0);

insert into SISSEGUMD.ac_rol (ROLCOD,DESCRIPCION,SITUACION,SIGLAS,GRUPOCOD,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE,ESTADO,ADMIN)
	VALUES (315,'Rol Usuario','A','ROLE_USER',104,'ADMIN','ADMIN',sysdate,sysdate,1,0);


-- USUARIO
insert into SISSEGUMD.AC_ROL_X_OPERADOR	(USUCOD,ROLCOD,SITUACION,GRUPOCOD,FECING,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE,ESTADO)
	VALUES ('JPINEDA',314,'A',104,sysdate,'ADMIN','ADMIN',sysdate,sysdate,1);

-- PRIVILEGIOS
GRANT SELECT ON SISSEGUMD.PE_EMPLEADO_MINDEF TO SISPP;
GRANT SELECT ON SISSEGUMD.AC_SUCESOS TO SISPP;
GRANT SELECT ON SISSEGUMD.AC_ROL_X_OPERADOR TO SISPP;
GRANT SELECT ON SISSEGUMD.PE_EMPLEADO_MINDEF TO SISPP;
GRANT SELECT ON SISSEGUMD.AC_ROL TO SISPP;


-- VISTAS
CREATE OR REPLACE FORCE VIEW "SISPP"."UVW_USER" AS
  SELECT TO_NUMBER (E.DOCIDEN) AS ID,
            e.nombres as FIRST_NAME,
            e.apellidos as LAST_NAME,
            e.email as EMAIL,
            '' AS image_url,
            '' AS activation_key,
            '' AS reset_key,
            1 AS ACTIVATED,
            'es' as LANG_KEY,
            null AS reset_date,
            1 AS admin,
            S.LLAVE AS PASSWORD_HASH,
            lower(E.USUCOD) AS LOGIN,
            E.CODUNIDADMD AS CODUNIDAD,
            SYSDATE LAST_MODIFIED_DATE,
            'admin' LAST_MODIFIED_BY,
            SYSDATE CREATED_DATE,
            'admin' CREATED_BY
       FROM SISSEGUMD.AC_SUCESOS S
            INNER JOIN SISSEGUMD.PE_EMPLEADO_MINDEF E ON S.USUCOD = E.USUCOD
            INNER JOIN SISSEGUMD.AC_ROL_X_OPERADOR R ON E.USUCOD = R.USUCOD
            INNER JOIN
            (  SELECT MAX (CODSUC) CODSUC, USUCOD
                 FROM SISSEGUMD.AC_SUCESOS
             GROUP BY USUCOD
               HAVING MAX (CODSUC) >
                           (SELECT MAX (CODSUC)
                              FROM SISSEGUMD.AC_SUCESOS)
                         - 100000) D
               ON D.CODSUC = S.CODSUC
      WHERE R.SITUACION = 'A' AND E.SITCOD = 'A' AND R.GRUPOCOD = 104
   GROUP BY E.DOCIDEN,
            E.USUCOD,
            S.LLAVE,
            E.NOMBRES,
            E.apellidos,
            E.email,
            R.GRUPOCOD,
            E.CODUNIDAD;


CREATE OR REPLACE FORCE VIEW "SISPP"."UVW_AUTHORITY" AS
   SELECT ROLCOD AS IDROLE,
          SIGLAS AS NAME
     FROM SISSEGUMD.AC_ROL
    WHERE GRUPOCOD = 104;



CREATE OR REPLACE FORCE VIEW "SISPP"."UVW_USER_AUTHORITY" AS
  SELECT r.siglas AS AUTHORITY_NAME, E.DOCIDEN AS USER_ID
     FROM SISSEGUMD.AC_ROL_X_OPERADOR RO
          INNER JOIN SISSEGUMD.PE_EMPLEADO_MINDEF E ON RO.USUCOD = E.USUCOD
          INNER JOIN SISSEGUMD.AC_ROL R ON r.rolcod = ro.rolcod
    WHERE E.SITCOD = 'A' AND RO.SITUACION = 'A'
        AND RO.GRUPOCOD = 104;
